### ISSUE TITLE
DG Comments

### ISSUE THREAD

**Issue by nishanthelango** [AY2021S1-CS2113T-W13-4/tp#114]
- [x] (Figure 3.1-2) This part of the sequence diagram is unclear: 
 
![image](https://user-images.githubusercontent.com/37863640/97536596-5d219d80-19f8-11eb-9c06-3665d7a1e5b4.png)

- [x] (Figure 3.1-2) Consider pointing the arrow to the top of the activation bar to make it clearer: 
![image](https://user-images.githubusercontent.com/37863640/97536621-66126f00-19f8-11eb-8259-bba11e6355de.png)

- [x] (Figure 4.2-1) Try to keep the activation bars opaque so that the lifelines can’t be seen behind them.
![image](https://user-images.githubusercontent.com/37863640/97536636-6d397d00-19f8-11eb-84be-e5bc1b09a772.png)

- [x] (Figure 4.5-1) Can this be separated into 2 activation bars?
![image](https://user-images.githubusercontent.com/37863640/97536691-817d7a00-19f8-11eb-97ce-18b4d7077169.png)

- [x] (Figure 4.5-1) Consider breaking up the EditNotesCommand activation bar. There should be a separate activation bars for each method call.
![image](https://user-images.githubusercontent.com/37863640/97536711-8a6e4b80-19f8-11eb-80a8-5aa06c371db9.png)

- [x] (Figure 4.6-1) Are these self-invocations? If they’re just variable assigments, they can be omitted. 
![image](https://user-images.githubusercontent.com/37863640/97536727-91955980-19f8-11eb-9c61-f38abe1bd965.png)

- [x] (Figure 4.8-1) The activation bar can be extended slightly to make it clearer where the return arrow is pointing.
![image](https://user-images.githubusercontent.com/37863640/97536745-98bc6780-19f8-11eb-93a1-c6ed94dad8b4.png)

**Comment by daniellimzj** [comment]
All fixed in various pull requests
